title: lenorix

remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-coffeescript
- jekyll-default-layout
- jekyll-gist
- jekyll-github-metadata
- jekyll-optional-front-matter
- jekyll-paginate
- jekyll-readme-index
- jekyll-titles-from-headings
- jekyll-relative-links
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-tailwindcss
