title: lenorix
description: Innovative tech solutions for business growth, creating apps, webs and other software to simplify your life.
repository: lenorix/lenorix.github.io
url: https://lenorix.com

remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
